// Generated by scripts/sync-sdk-source.ts. Do not edit by hand.
export const SDK_SOURCE = {
  "packageName": "@composio/core",
  "packageVersion": "0.17.0",
  "gitHead": "4fae6e54d5c150fba955cc5fa314281da5a1e064",
  "sourceKind": "installed-package",
  "concepts": [
    {
      "id": "c-client",
      "name": "new Composio({ apiKey })",
      "sourcePath": "src/composio.ts",
      "sourceSymbol": "Composio",
      "sourceHash": "ce396d533358",
      "evidence": "export class Composio"
    },
    {
      "id": "c-tools-get",
      "name": "composio.tools.get",
      "sourcePath": "src/models/Tools.ts",
      "sourceSymbol": "Tools.get",
      "sourceHash": "1c12074b51c2",
      "evidence": "async get(...)"
    },
    {
      "id": "c-auth-configs",
      "name": "composio.authConfigs.create",
      "sourcePath": "src/models/AuthConfigs.ts",
      "sourceSymbol": "AuthConfigs.create",
      "sourceHash": "0809f944db79",
      "evidence": "async create(...)"
    },
    {
      "id": "c-connected-accounts",
      "name": "composio.connectedAccounts.initiate",
      "sourcePath": "src/models/ConnectedAccounts.ts",
      "sourceSymbol": "ConnectedAccounts.initiate",
      "sourceHash": "7df970f0d5c6",
      "evidence": "async initiate(...)"
    },
    {
      "id": "c-execute",
      "name": "composio.tools.execute",
      "sourcePath": "src/models/Tools.ts",
      "sourceSymbol": "Tools.execute",
      "sourceHash": "1c12074b51c2",
      "evidence": "async execute(...)"
    },
    {
      "id": "c-sessions",
      "name": "composio.sessions.create",
      "sourcePath": "src/models/ToolRouter.ts",
      "sourceSymbol": "ToolRouter.create",
      "sourceHash": "de070755e955",
      "evidence": "async create(...)"
    },
    {
      "id": "c-toolkits",
      "name": "composio.toolkits.get",
      "sourcePath": "src/models/Toolkits.ts",
      "sourceSymbol": "Toolkits.get",
      "sourceHash": "f9bf9bebcd1a",
      "evidence": "async get(...)"
    },
    {
      "id": "c-triggers",
      "name": "composio.triggers.create",
      "sourcePath": "src/models/Triggers.ts",
      "sourceSymbol": "Triggers.create",
      "sourceHash": "afe647ebe8b6",
      "evidence": "async create(...)"
    },
    {
      "id": "c-tool-bind",
      "name": "framework tool adapter",
      "sourcePath": "src/models/Tools.ts",
      "sourceSymbol": "Tools.get + Tools.execute",
      "sourceHash": "1c12074b51c2",
      "evidence": "get schema, adapt, execute"
    }
  ]
} as const;
